### ISSUE TITLE
보유종목이 많을 때 오류

### ISSUE THREAD

**Issue by atmoskr** [breadum/kiwoom#16]
안녕하세요. 
코드는 Tutorial 의 5번 "TR Data.py" 에서 나고, 보유종목이 많을 때, 다음 과 같은 에러가 나네요.
오류 내용입니다.

[GetPCIdentity] VER 3.2.0.0  build 2015.8.12

로그인 정상처리

* 시스템 점검
  - 월 ~ 토 : 05:05 ~ 05:10
  - 일 : 04:00 ~ 04:30

Bot.deposit() 호출

화면번호: 0000, 요청이름: deposit, TR코드: opw00001
[100000] 모의투자 조회완료

        Server.deposit(scr_no, rq_name, tr_code, record_name, prev_next) 호출
        Server.deposit(scr_no, rq_name, tr_code, record_name, prev_next) 종료
Bot.deposit() 종료
Bot.balance(prev_next) 호출

화면번호: 0000, 요청이름: balance, TR코드: opw00018
[100000] 모의투자 조회가 계속됩니다. 계속조회시 다음키를 누르십시오.

        Server.balance(scr_no, rq_name, tr_code, record_name, prev_next) 호출
Bot.balance(prev_next) 호출
Bot.balance(prev_next) 종료

화면번호: 0000, 요청이름: balance, TR코드: opw00018
[100000] 모의투자 조회가 계속됩니다. 계속조회시 다음키를 누르십시오.

        Server.balance(scr_no, rq_name, tr_code, record_name, prev_next) 호출
Bot.balance(prev_next) 호출
Bot.balance(prev_next) 종료

화면번호: 0000, 요청이름: balance, TR코드: opw00018
[100000] 모의투자 조회가 계속됩니다. 계속조회시 다음키를 누르십시오.

        Server.balance(scr_no, rq_name, tr_code, record_name, prev_next) 호출
Bot.balance(prev_next) 호출
Bot.balance(prev_next) 종료

화면번호: 0000, 요청이름: balance, TR코드: opw00018
[100000] 모의투자 조회가 계속됩니다. 계속조회시 다음키를 누르십시오.

        Server.balance(scr_no, rq_name, tr_code, record_name, prev_next) 호출
Bot.balance(prev_next) 호출
Traceback (most recent call last):
  File "c:\Users\Administrator\OneDrive - DZS\dev\ktrader-dev\kydwin\kiwoom\core\connector.py", line 386, in wrapper
    slot(*args)
  File "c:\Users\Administrator\OneDrive - DZS\dev\ktrader-dev\kydwin\5. TR Data.py", line 352, in balance
    fn(prev_next)  # call signal function again to receive remaining data
  File "c:\Users\Administrator\OneDrive - DZS\dev\ktrader-dev\kydwin\5. TR Data.py", line 217, in balance
    self.api.comm_rq_data('balance', tr_code, prev_next, '0000')
  File "c:\Users\Administrator\OneDrive - DZS\dev\ktrader-dev\kydwin\kiwoom\config\error.py", line 73, in wrapper
    print(f'\nAn error occurred from {fn.__name__}.\n  * {msg(out)}')
  File "c:\Users\Administrator\OneDrive - DZS\dev\ktrader-dev\kydwin\kiwoom\config\error.py", line 50, in msg
    etype, msg = ERR[ecode]
KeyError: -211

**Comment by breadum** [comment]
안녕하세요,
오류 코드 -211을 보니 계좌 정보나 보유종목 관련 조회가 
초당 5번을 초과했을 때 발생하는 오류로 확인됩니다.  
https://www.kiwoom.com/h/common/bbs/VBbsBoardBWOAZView

아래처럼 수정하시면 잘 작동할 것 같습니다.
[튜토리얼 파일]도 같이 업데이트 해두었습니다.
오류 제보 감사드립니다.

```
from kiwoom import Bot
from PyQt5.QtTest import QTest

class Bot(Bot):
    ...
    def balance(prev_next='0'):
        ...
        # 연속 조회 제한 회피를 위한 딜레이 0.5초
        if prev_next != '0':
            QTest.qWait(500) 

        # TR Data 요청함수 API 개발가이드
        # > help(Kiwoom.comm_rq_data)
        # > comm_rq_data(rq_name, tr_code, prev_next, scr_no)
        self.api.comm_rq_data('balance', tr_code, prev_next, '0000')
        ...
```

[튜토리얼 파일]: https://github.com/breadum/kiwoom/blob/main/tutorials/5.%20TR%20Data.py

**Comment by atmoskr** [comment]
감사합니다~~
